//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Solution.API.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://deawiwaird001.syngentaaws.org/Airim.GDC")]
        public string API_URL_R3 {
            get {
                return ((string)(this["API_URL_R3"]));
            }
            set {
                this["API_URL_R3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bearer eyJraWQiOiJpd2tkRFBDMXBIQXhwK2ZNXC93aWtKYkwrVU9hV21wUUx4S0dsRFFvMHpqZz0iLC" +
            "JhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoia09wanZfQ1RCcVBVSWJraFVDTFllQSIsInN1YiI6IjRjM" +
            "DkxZDcxLTA3NTEtNDYwYi04ZTQyLTUzZTllM2I4ZWVhOSIsImNvZ25pdG86Z3JvdXBzIjpbImV1LWNlb" +
            "nRyYWwtMV92cW53Y2VqN3RfQXp1cmUtR0RDIl0sImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNzIjoia" +
            "HR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tXC9ldS1jZW50cmFsL" +
            "TFfdnFud2Nlajd0IiwiY29nbml0bzp1c2VybmFtZSI6IkF6dXJlLUdEQ19zOTU5NjgwIiwicHJlZmVyc" +
            "mVkX3VzZXJuYW1lIjoiczk1OTY4MCIsImdpdmVuX25hbWUiOiJTYWxhbWEgTW9oYW1lZCAoZXh0KSBHQ" +
            "kVYIiwibm9uY2UiOiJoSjM1MzExeDVlVURTcTlnQVVaZGhSa3RYbDdhY3lnekVkbUNLVFFkQkFTRW0wR" +
            "zg3NnViUnkyMVU1WHJRNHhfdHVDTHF4YWEwanVzVUpnM2tDZHF6Z00tbXNHeV9PQzgzTTRIZjhFd0lZb" +
            "zFMVDZnUl9HazdVOVd4LWpPcndENUFBdkc5M2xBM0dRYjE3ZFhlcnhKX1dGR0xuRGVDZk82dFhaaVk5e" +
            "TV4YUUiLCJhdWQiOiI2dW5vODVicmNnYzl1NGtjNGlrZmFjc2ZjbiIsImlkZW50aXRpZXMiOlt7InVzZ" +
            "XJJZCI6InM5NTk2ODAiLCJwcm92aWRlck5hbWUiOiJBenVyZS1HREMiLCJwcm92aWRlclR5cGUiOiJTQ" +
            "U1MIiwiaXNzdWVyIjoiaHR0cHM6XC9cL3N0cy53aW5kb3dzLm5ldFwvMDYyMTlhNGEtYTgzNS00NGQ1L" +
            "WFmYWYtMzkyNjM0M2JmYjg5XC8iLCJwcmltYXJ5IjoidHJ1ZSIsImRhdGVDcmVhdGVkIjoiMTU2OTc2N" +
            "TQyNDI0OCJ9XSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1NzgyMjUzNjAsIm5hbWUiOiJzO" +
            "TU5NjgwIiwiZXhwIjoxNTc4MjI4OTYwLCJpYXQiOjE1NzgyMjUzNjAsImVtYWlsIjoiTW9oYW1lZC5TY" +
            "WxhbWFAaXR3b3J4LmNvbSJ9.e4Hbw8kjoB0NlpC84Q2LeFXCalriU3nTgT7PmTyVGAlgrR1BiA0q25RH" +
            "aQf4jlBpfsGzLmWJiTREwC4_twg4ru9hH_drWMeMiQxqqhJ2eAAhQZKVA0HYm10F5oWZ5fxh0C4soOKV" +
            "ssozk8PMrngI84BAulDfowq2ujxSD01mGjr-kPK0yq3Em2yFy0j492vhV3C5eahrYt_-bhUriZ0S9DcY" +
            "Pw60TB8ayFw1KrEyOVwvzSev8EpWvaukVHnz68Q4UGUGekyMRubtAXFyM-LSmzVV35515khJzekw4qxg" +
            "bwUBFYebcFLoGLcv13afxviwzll4DAf6lupewQ3i8RK1zg")]
        public string Token {
            get {
                return ((string)(this["Token"]));
            }
            set {
                this["Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/CheckIn/StartCheckIn")]
        public string StartCheckIn {
            get {
                return ((string)(this["StartCheckIn"]));
            }
            set {
                this["StartCheckIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/CheckIn/SaveCheckInObject")]
        public string SaveCheckInObject {
            get {
                return ((string)(this["SaveCheckInObject"]));
            }
            set {
                this["SaveCheckInObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://deawiwairs001.syngentaaws.org/Airim.GDC")]
        public string API_URL_R1 {
            get {
                return ((string)(this["API_URL_R1"]));
            }
            set {
                this["API_URL_R1"] = value;
            }
        }
    }
}
